# Generated by Django 2.2.1 on 2019-05-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('pwd', models.CharField(max_length=20, verbose_name='密码')),
                ('cpwd', models.CharField(max_length=20, verbose_name='确认密码')),
                ('email', models.EmailField(default='1143108768@qq.com', max_length=254)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
            },
        ),
    ]
